spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filemanager?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ejk127ekqls$

  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

google:
  clientId: 736947599096-mtl5f0tn2kc2arrv3o15k23fd1ticrl7.apps.googleusercontent.com
  clientSecret: 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
  tokenUrl: https://oauth2.googleapis.com/token



